kind: pipeline
type: docker
name: default

steps:
- name: golang_test
  image: golang:1.14-alpine
  environment:
    CGO_ENABLED: 0
  commands:
    - go test -mod=vendor -cover

- name: docker
  image: plugins/docker
  settings:
    repo: rain123473/gggcp
    dockerfile: Dockerfile
    auto_tag: true
    purge: true
    username:
        from_secret: docker_account
    password:
        from_secret: docker_password